swagger: "2.0"
info:
  title: Insure API
  description: API for managing insurance policies
  version: 1.0.0
host: localhost:3000
basePath: /
schemes:
- http
securityDefinitions:
  apiKeyAuth:
    type: apiKey
    in: header
    name: x-api-key
    description: The API key for authentication
paths:
  /policies/{id}:
    get:
      description: "Get a policy by ID"
      parameters:
      - name: id
        in: path
        required: true
        type: string
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
    put:
      description: "Update a policy by ID"
      parameters:
      - name: id
        in: path
        required: true
        type: string
      - name: x-api-key
        in: header
        type: string
      - name: body
        in: body
        schema:
          type: object
          properties:
            productId:
              example: any
              type: string
              optional: true
            customerName:
              type: string
              example: any
              optional: true
            startDate:
              example: any
              optional: true
            endDate:
              example: any
              optional: true
            premium:
              type: number
              example: "300"
              optional: true
            status:
              type: string
              optional: true
              example: any
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
    delete:
      description: "Delete a policy by ID"
      parameters:
      - name: id
        in: path
        required: true
        type: string
      - name: x-api-key
        in: header
        type: string
      responses:
        "204":
          description: No Content
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
  /policies:
    get:
      description: "Get policies by customer name"
      parameters:
      - name: customerName
        in: query
        type: string
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
    post:
      description: "Create a new policy"
      parameters:
      - name: x-api-key
        in: header
        type: string
      - name: body
        in: body
        schema:
          type: object
          properties:
            productId:
              type: string
              example: any
            startDate:
              type: string
              example: any
            endDate:
              type: string
              example: any
            customerName:
              type: string
              example: any
            premium:
              type: number
              example: "300"
            status:
              example: any
      responses:
        "201":
          description: Created
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
        "500":
          description: Internal Server Error
